update_templates: true
severities:
  - info
  - low
  - medium
  - high
  - critical
tags:
  - cve
  - rce
  - sqli
  - xss
  - ssti
  - lfi
  - ssrf
  - crlf
  - prototype-pollution
  - deserialization
  - auth-bypass
  - config
  - misconfig
  - exposed-panels
  - default-logins
  - tech
  - takeover
  - dast
  - dast-sqli
  - dast-xss
rate_limit: 100
concurrency: 50
timeout: 10
retries: 2
follow_redirects: true
headless: true
extra_args: >
  -dast
  -stats
  -random-agent
  -duc
  -rl 100